### ISSUE TITLE
Describe a "contribution" guideline

### ISSUE THREAD

**Issue by lootsy** [cogneon/lernos-for-you#17]
Does it makes sense to have a CONTRIBUTING.md in the repo.

I'm unsure about how to create pull request. How can I support your workflow so that merging is a really easy action for you?

Thx.

**Comment by simondueckert** [comment]
Sorry, I had not much time to handle the pull requests the last two weeks. I planned to have a look at it on monday. Are you experienced how to handle contributions on github efficiently. Should we have a short call next week?

**Comment by lootsy** [comment]
I'm not really an experienced github user. Of course we can call.
I'm not sure what you mean by "effieciently".

Again: no need to hurry. I don't want to be a reason for any pressure may occur.

**Comment by lootsy** [comment]
Another idea: maybe write access to this repo for "approved" contributors?
