### ISSUE TITLE
https link läuft ins leere

### ISSUE THREAD

**Issue by BjoernSchotte** [cogneon/lernos-for-you#170]
Auf https://github.com/cogneon/lernos-for-you/blob/master/README.md wird auf https://lernos.org/ referenziert, das zu einem ERR_SSL_PROTOCOL_ERROR im Chrome führt. Ein Aufruf von http://lernos.org/ geht jedoch. SSL-Cert Problem?

**Comment by BjoernSchotte** [comment]
@simondueckert any news on this?

**Comment by simondueckert** [comment]
Bei mir geht der Link, kann keinen Fehler feststellen. Ist das bei dir immer noch so? Wenn nicht, schließe ich den Issue.

**Comment by BjoernSchotte** [comment]
Funktioniert jetzt wieder.
