### ISSUE TITLE
Define standard for kata definition

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-for-you#89]
With more lernOS guides being developped there should be a standard format to define katas (length, structure, difficulty level, links, necessary time etc.).

From lernOS template:
- Title/Titel (chapter title)
- Introduction/Einleitung (incl. goal) (no chapter, text below chapter)
- Instruction/Anleitung

Metadata like category, time needed, level etc. will follow in the future

**Comment by rednaxelaesor** [comment]
Based on the idea of the app "LISA" for the Libarating Structures https://play.google.com/store/apps/details?id=de.holisticon.app.ls&hl=de=en.holisticon.app.ls&hl=de the KATAS should get standardized TAGs. You can then filter them by theme, time, context, etc.
E.G.: 
* Length
* GUIDE DAY :OKR, GTD, WOL, PODCAST...
* networking
* appreciation
* etc.

I have a phone call tomorrow with the founder of StudySmarter https://www.studysmarter.de/ 
Let's see what becomes of it ...

Translated with www.DeepL.com/Translator
