### ISSUE TITLE
Add future backwards kata to week 0

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-for-you#94]
The future backwards method can help to sharpen vision and derive objectives from it.

**Comment by rednaxelaesor** [comment]
Hi Simon, diese Kata war ja in einer ganz frühen Version (vor Version 1.0 glaube ich) mal drin. Ich hatte damals angemerkt, dass die Übung schon sehr anspruchsvoll & zeit beansprucht und ggf. etwas später im laufe der 12 Wochen durchgeführt werden sollte, wenn alle schon etwas fitter mit Katas an sich sind. Dann ist sie ja ganz raus genommen worden, was ich persönlich schade fand, da es eine echt gute Übung ist.
Jetzt freue ich mich, wenn sie wieder reinkommt.
LG ALex

**Comment by simondueckert** [comment]
> Jetzt freue ich mich, wenn sie wieder reinkommt.

Ja das war damals noch etwas früh. Im [letzten EDMOD Meetup](https://community.cogneon.de/t/edmod-meetup-2018/267) hatte Helmut schon vorgeschlagen, Future Backwards im lernOS Expert Debriefing Leitfaden aufzunehmen. Helmut hat das Future Backwards aktuell auch in sein [Learning Sprint Booklet](https://good-transfer.com/2019/05/09/immer-der-neugier-nach/) (S. 12) eingebaut.

Außerdem wird der Lernpfad in den zukünftigen Versionen neben dem WOL-lite-Lernpfad noch um Lernpfade zu GTD und OKR ergänzt werden. Bei GTD gibt es die sog. [sechs Fokus-Horizonte](https://gettingthingsdone.com/2011/01/the-6-horizons-of-focus/) und bei OKR die Mission und Vision (s.a. [OKR Zyklus](https://www.workpath.com/magazine/von-der-vision-zur-sichtbaren-strategieumsetzung-der-okr-prozess/)). Und genau dafür werden wir dann diese Kata wieder brauchen. Zeit sie wieder aufzunehmen, bin auch ein großer Fan davon.

**Comment by simondueckert** [comment]
offen ist für mich noch ein bisschen die Frage, ob die Kata in Woche 0 oder 12 kommt. Tendenz bei mir ist Woche 0, weil die langfristige Perspektive sich auf die kurz-/mittelfristigen Ziele auswirken kann. Die Woche 12 sehe ich eher als Review der Sprint-Ergebnisse (wurde die Ziele erreicht) und Retrospektive des lernOS Prozesses (was machen wir beim nächsten Mal anders?). Aber sicher bin ich mir nicht.

**Comment by rednaxelaesor** [comment]
> offen ist für mich noch ein bisschen die Frage, ob die Kata in Woche 0 oder 12 kommt.
Das kann ich sehr gut nachvollziehen. Didaktisch wäre es am Ende besser, inhaltlich klar am Anfang.
Oder so: Wenn wir davon ausgehen, das die TN immer wieder iterieren, ist Woche 12 quasi der Beginn für den nächsten Circle 0. Etwas hergeholt, aber wenn wir den NOOB Pfad zum Kennenlernen/Einführen  verstehen, dann ist der zweite Circle eigentlich der Erste, beim ich ich mich um meine Visionen kümmere - also mich tiefer mit mir und meinen Zielen auseinandersetze.
